### ISSUE TITLE
Remember last selections

### ISSUE THREAD

**Issue by bkis1** [Stefouch/simultaneous-cards-fvtt#2]
### Description

It would be a sure time saver if this remembered the last selections on the setup screen (player & deck)...its a bit of a chore to set that up each time.  But thanks for the great work!

### Suggested solution

Bonus addition (of much less importance):  Give an option to discard the used cards.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Stefouch** [comment]
I will add a `Restart` button like suggested in #3
