### ISSUE TITLE
Offer a way to trigger post-reveal macros

### ISSUE THREAD

**Issue by Lim-Dul** [Stefouch/simultaneous-cards-fvtt#4]
### Description

Currently, there is no way of triggering post-reveal functionality in the module (as far as I am aware). It would be nice to be able to trigger some sort of effect after the cards have been revealed through a dedicated scripting trigger or some sort of setting. E.g. roll on a table.

### Suggested solution

As described above this could be handled by a setting within the module, a scriptable event that would be fired after revealing cards or maybe a configurable button in the post-reveal dialog.

### Additional context

This would be especially useful in Blade Runner RPG chase scenes where you have to generate a randomized (context-sensitive) obstacle for each round of the chase.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Stefouch** [comment]
Can you try to catch the reveal event like this ?
```js
game.socket.on('module.simultaneous-cards', data => {
  console.log(data);
  if (data.event === 'reveal') {
    console.log('Reveal Event!');
  }
});
```

**Comment by Stefouch** [comment]
Oh wait, it'll only work when other players reveal a card, not you.
Okay, I'll find a solution
