### ISSUE TITLE
Is there a way to draw the cards at random without seeing the cards in the deck?

### ISSUE THREAD

**Issue by stevenagl12** [Stefouch/simultaneous-cards-fvtt#5]
### Description

I was hoping there was a way in Simultaneous Cards to have the players/GM randomly pull face down cards from the deck, then reveal them for the final win?

### Suggested solution

An option within the card deck, or the icon to allow players and GM to select from shuffled face down cards.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Stefouch** [comment]
I will develop that feature
